services:
  postgres:
    image: postgres:15-alpine
    container_name: receipt-processor-db
    environment:
      POSTGRES_DB: receipt_processor
      POSTGRES_USER: receipt_user
      POSTGRES_PASSWORD: receipt_password
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - receipt-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U receipt_user -d receipt_processor"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: receipt-processor-app
    environment:
      DATABASE_URL: postgresql://receipt_user:receipt_password@postgres:5432/receipt_processor
      API_HOST: 0.0.0.0
      API_PORT: 80
      DEBUG: false
    ports:
      - "80:80"
    networks:
      - receipt-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import httpx; httpx.get('http://localhost:80/api/health')\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  receipt-network:
    driver: bridge

volumes:
  postgres-data: